---
engines:
  csslint:
    enabled: true
    checks:
      read-error:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: false
  phpmd:
    enabled: true
    checks:
      CleanCode/StaticAccess:
        enabled: false
      Controversial/CamelCaseClassName:
        enabled: false
      Controversial/CamelCaseParameterName:
        enabled: false
      Controversial/Superglobals:
        enabled: false
      UnusedFormalParameter:
        enabled: false
      UnusedLocalVariable:
        enabled: false
      UnusedPrivateMethod:
        enabled: false
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- includes/cpt/**/*
- public/js/jquery.min.js
- vendor/**/*
